const logoData = [
  { name: "A&A", location: "2-1-7,,12", size: "", quantity: 5 },
  { name: "Abp", location: "2-4-17", size: "", quantity: 1 },
  { name: "Adrian", location: "2-8-7,8", size: "", quantity: 2 },
  { name: "Agata", location: "4-5-9,,11", size: "", quantity: 3 },
  { name: "Agata", location: "4-7-9", size: "", quantity: 1 },
  { name: "Alfa salon opty", location: "2-3-22", size: "", quantity: 1 },
  { name: "Alfa salon opty", location: "2-4-23", size: "", quantity: 1 },
  { name: "Allspice", location: "1-4-3,4,5", size: "", quantity: 3 },
  { name: "Amari", location: "1-3-15, 16", size: "", quantity: 2 },
  { name: "Amari", location: "1-4-17", size: "", quantity: 1 },
  { name: "Amari", location: "1-5-14", size: "", quantity: 1 },
  { name: "Amari", location: "1-5-17", size: "", quantity: 1 },
  { name: "Amcor", location: "4-6-11", size: "", quantity: 1 },
  { name: "Ameds", location: "1-9-12,, 16", size: "", quantity: 5 },
  { name: "Amlux", location: "1-2-5", size: "", quantity: 1 },
  { name: "Animal care center", location: "1-8-15", size: "", quantity: 1 },
  { name: "Apteka", location: "1-7-8,, 9,,10", size: "", quantity: 3 },
  { name: "Apteka Leko", location: "1-2-1", size: "", quantity: 1 },
  { name: "Arche Lublin", location: "2-9-15,,18", size: "", quantity: 3 },
  { name: "Arche Lublin", location: "4-4-3", size: "", quantity: 1 },
  { name: "Arche Naleczo", location: "1-6-1", size: "", quantity: 1 },
  { name: "Arche naleczo", location: "1-5-1, 2", size: "", quantity: 2 },
  { name: "Arche naleczo", location: "3-6-5", size: "", quantity: 1 },
  { name: "Astramed", location: "2-3-14", size: "115x200", quantity: 1 },
  { name: "Astramed", location: "2-3-16", size: "115x240", quantity: 1 },
  { name: "Astramed", location: "2-8-20", size: "150x250", quantity: 1 },
  { name: "Astramed", location: "3-6-1", size: "", quantity: 1 },
  { name: "Astramed", location: "3-6-2", size: "", quantity: 1 },
  { name: "Astramed", location: "4-7-8", size: "", quantity: 1 },
  { name: "Atelier fryzur", location: "2-11-6", size: "", quantity: 1 },
  { name: "Attica", location: "4-7-7", size: "", quantity: 1 },
  { name: "Auto nobile Ford", location: "2-2-3", size: "", quantity: 1 },
  { name: "BAIC", location: "1-2-5", size: "", quantity: 1 },
  { name: "BAIC", location: "1-2-6", size: "", quantity: 1 },
  { name: "BAIC", location: "1-2-8", size: "", quantity: 1 },
  { name: "BCB", location: "4-2-5,, 7", size: "", quantity: 3 },
  { name: "BWM Electronic", location: "4-4-1", size: "", quantity: 1 },
  { name: "Basf", location: "4-2-9,, 10", size: "", quantity: 2 },
  { name: "Bcb", location: "1-8-2", size: "", quantity: 1 },
  { name: "Beaute&barber", location: "1-6-5", size: "", quantity: 1 },
  { name: "Beauty centr estet", location: "1-8-11", size: "", quantity: 1 },
  { name: "Beauty experts", location: "1-1-22", size: "", quantity: 1 },
  { name: "Beauty medical", location: "2-7-25", size: "", quantity: 1 },
  { name: "Benepol", location: "1-6-22", size: "", quantity: 1 },
  { name: "Big sale shop", location: "4-4-6", size: "", quantity: 1 },
  { name: "Biologique recherche", location: "1-1-21", size: "", quantity: 1 },
  { name: "Bobrowy dwór", location: "2-6-5", size: "", quantity: 1 },
  { name: "Bosko wlosko", location: "2-5-25", size: "", quantity: 1 },
  { name: "Bricomarche", location: "4-4-10,11", size: "", quantity: 2 },
  { name: "Bs, Bw wys mazo", location: "1-9-26", size: "", quantity: 1 },
  { name: "Butelkownia", location: "3-2-5,6", size: "", quantity: 2 },
  { name: "CT card", location: "1-8-25", size: "", quantity: 1 },
  { name: "Campanile", location: "1-4-1, 2", size: "", quantity: 2 },
  { name: "Campanile", location: "3-3-1", size: "", quantity: 1 },
  { name: "Canal +", location: "4-5-7,8", size: "", quantity: 2 },
  { name: "Candy park", location: "4-1-1,2", size: "", quantity: 2 },
  { name: "Casa mia frog", location: "1-11-24", size: "", quantity: 1 },
  { name: "Cbl", location: "3-8-1", size: "", quantity: 1 },
  { name: "Cbl", location: "4-4-4,5", size: "", quantity: 2 },
  { name: "Cbl łódź", location: "4-6-3", size: "", quantity: 1 },
  { name: "Centrodent", location: "1-3-5", size: "", quantity: 1 },
  { name: "Centrum dentystyczne", location: "1-2-18", size: "", quantity: 1 },
  { name: "Centrum med ogro", location: "3-4-1, 2", size: "", quantity: 2 },
  { name: "Centrum med ogrod", location: "2-6-21, 22", size: "", quantity: 2 },
  { name: "Centrum strzeleckie", location: "3-5-4", size: "", quantity: 1 },
  { name: "Cis frampol", location: "2-6-7,, 8", size: "", quantity: 2 },
  { name: "Citi handlowy", location: "1-9-8,,11", size: "", quantity: 4 },
  { name: "Colibra", location: "1-7-5", size: "", quantity: 1 },
  { name: "Comet", location: "3-4-4", size: "", quantity: 1 },
  { name: "Comitor", location: "1-8-9", size: "", quantity: 1 },
  { name: "Comitor", location: "3-7-10", size: "", quantity: 1 },
  { name: "Concept", location: "3-4-3", size: "", quantity: 1 },
  { name: "Cosmet", location: "1-4-7", size: "", quantity: 1 },
  { name: "Cud miód", location: "1-10-8,,9", size: "", quantity: 2 },
  { name: "Cupra studio wawa", location: "3-5-6", size: "", quantity: 1 },
  { name: "DHL", location: "1-1-14", size: "", quantity: 1 },
  { name: "DHL", location: "1-1-15", size: "", quantity: 1 },
  { name: "DHL", location: "1-3-12, 13, 14", size: "", quantity: 1 },
  { name: "Daito sushi", location: "1-7-1,, 2", size: "", quantity: 2 },
  { name: "Dbk", location: "3-3-10", size: "", quantity: 1 },
  { name: "Dbk", location: "4-3-4,5", size: "", quantity: 2 },
  { name: "Dcp", location: "1-2-10", size: "", quantity: 2 },
  { name: "Dcp", location: "1-2-11", size: "", quantity: 1 },
  { name: "Denis", location: "1-12-24", size: "", quantity: 1 },
  { name: "Dentis", location: "3-8-2", size: "", quantity: 1 },
  { name: "Der clinic", location: "2-10-17", size: "", quantity: 1 },
  { name: "Der elefant", location: "2-0-2", size: "", quantity: 1 },
  { name: "Dewocjonalia", location: "2-11-10", size: "", quantity: 1 },
  { name: "Diasfera", location: "1-12-20,,23", size: "", quantity: 4 },
  { name: "Diaverum", location: "1-5-3", size: "", quantity: 1 },
  { name: "Diazzuro", location: "2-2-22", size: "", quantity: 1 },
  { name: "Dobratu", location: "2-1-6", size: "", quantity: 1 },
  { name: "Dobratu", location: "2-2-5", size: "", quantity: 1 },
  { name: "Dobratu", location: "2-2-6", size: "", quantity: 1 },
  { name: "Dobratu", location: "2-2-7", size: "", quantity: 1 },
  { name: "Dock 19", location: "1-1-17", size: "", quantity: 1 },
  { name: "Domoteka - paleta", location: "", size: "", quantity: 0 },
  { name: "Doz", location: "1-2-26", size: "", quantity: 1 },
  { name: "Doz", location: "2-11-21,,24", size: "", quantity: 4 },
  { name: "Doz", location: "3-3-8,9", size: "", quantity: 2 },
  { name: "Doz", location: "3-6-7,, 9", size: "", quantity: 3 },
  { name: "Dr Gerard", location: "1-2-21", size: "", quantity: 1 },
  { name: "Drilango", location: "1-9-19,, 20", size: "", quantity: 2 },
  { name: "Driveland (mała)", location: "2-10-7", size: "", quantity: 1 },
  { name: "Driveland", location: "3-2-4", size: "", quantity: 1 },
  { name: "Dsm firmenich", location: "2-2-8", size: "", quantity: 1 },
  { name: "Eco babice", location: "2-7-16", size: "", quantity: 1 },
  { name: "Eco classic", location: "2-3-10", size: "", quantity: 1 },
  { name: "Eco classic", location: "2-5-1,, 2", size: "", quantity: 2 },
  { name: "Eco", location: "1-4-16", size: "", quantity: 1 },
  { name: "Eduventura", location: "3-2-9", size: "", quantity: 1 },
  { name: "El box", location: "2-10-21", size: "", quantity: 1 },
  { name: "El box", location: "4-7-11", size: "", quantity: 1 },
  { name: "Ela", location: "1-6-6", size: "", quantity: 1 },
  { name: "El box", location: "2-9-22", size: "", quantity: 1 },
  { name: "Elsner", location: "1-10-18,, 21", size: "", quantity: 4 },
  { name: "Emil frey", location: "4-5-2, 3", size: "", quantity: 2 },
  { name: "Emsur", location: "3-5-7", size: "", quantity: 1 },
  { name: "Energym", location: "1-11-11", size: "", quantity: 1 },
  { name: "Ered", location: "1-12-22", size: "", quantity: 2 },
  { name: "Eskulap", location: "1-1-24", size: "", quantity: 1 },
  { name: "Eskulap", location: "1-2-24", size: "", quantity: 1 },
  { name: "Eskulap", location: "1-3-23,24", size: "", quantity: 2 },
  { name: "Euro rent zala", location: "2-2-4", size: "", quantity: 1 },
  { name: "Euro rent zala", location: "2-3-4", size: "", quantity: 1 },
  { name: "Euroglass", location: "4-2-11", size: "", quantity: 1 },
  { name: "Eva best med", location: "1-8-16", size: "", quantity: 1 },
  { name: "Eva park", location: "2-3-6,,8", size: "", quantity: 3 },
  { name: "Eva park", location: "3-4-11", size: "", quantity: 1 },
  { name: "Faller bia", location: "4-6-6,7", size: "", quantity: 2 },
  { name: "Faller pomar", location: "4-6-5", size: "", quantity: 1 },
  { name: "Family pets", location: "1-11-27", size: "", quantity: 1 },
  { name: "Faurecia", location: "2-6-23", size: "", quantity: 1 },
  { name: "Fiat", location: "1-11-3", size: "", quantity: 1 },
  { name: "Filman", location: "1-7-23", size: "", quantity: 1 },
  { name: "Firmenich", location: "1-3-11", size: "", quantity: 1 },
  { name: "Flisac", location: "2-5-13,,15", size: "", quantity: 3 },
  { name: "Flisac", location: "4-3-3", size: "", quantity: 1 },
  { name: "Florapoint", location: "2-7-26", size: "", quantity: 1 },
  { name: "Florapoint", location: "2-8-25, 26", size: "", quantity: 2 },
  { name: "Flugger", location: "1-5-18,23", size: "", quantity: 6 },
  { name: "Flugger", location: "1-6-20", size: "", quantity: 1 },
  { name: "Flugger", location: "2-2-12,,18", size: "", quantity: 7 },
  { name: "Flugger", location: "2-3-12", size: "", quantity: 1 },
  { name: "Flugger", location: "2-3-13", size: "", quantity: 1 },
  { name: "Flugger", location: "2-3-17", size: "", quantity: 1 },
  { name: "Flugger", location: "2-3-9", size: "", quantity: 1 },
  { name: "Flugger", location: "2-8-16", size: "", quantity: 1 },
  { name: "Flugger", location: "2-8-23", size: "", quantity: 1 },
  { name: "Focus hotel", location: "2-2-23,,24", size: "", quantity: 2 },
  { name: "Fresh gelato", location: "1-7-4", size: "", quantity: 1 },
  { name: "Fuji film", location: "1-11-1,, 2", size: "", quantity: 2 },
  { name: "Fuji film", location: "3-7-1", size: "", quantity: 1 },
  { name: "Gabriella", location: "2-6-1", size: "", quantity: 1 },
  { name: "Galeria koloru", location: "1-4-18", size: "", quantity: 1 },
  { name: "Galileo", location: "1-5-4,-,6", size: "", quantity: 3 },
  { name: "Galileo", location: "1-6-3", size: "", quantity: 1 },
  { name: "Galileo", location: "1-6-4", size: "", quantity: 1 },
  { name: "Galileo", location: "1-6-7", size: "", quantity: 1 },
  { name: "Gamma knife", location: "2-2-25", size: "", quantity: 1 },
  { name: "Gamma knife", location: "4-4-6", size: "", quantity: 1 },
  { name: "Garden party", location: "1-10-22", size: "", quantity: 1 },
  { name: "Garncarz", location: "2-2-19", size: "", quantity: 1 },
  { name: "Geberit", location: "3-5-8", size: "", quantity: 1 },
  { name: "Gmina Wiązowna", location: "1-8-13,, 14", size: "", quantity: 2 },
  { name: "Golden rosa", location: "2-1-14", size: "", quantity: 1 },
  { name: "Golden tulip", location: "4-3-6,7", size: "", quantity: 2 },
  { name: "Goś", location: "2-4-20,, 21", size: "", quantity: 2 },
  { name: "Grafotronic", location: "1-2-15", size: "", quantity: 1 },
  { name: "Grafotronic", location: "3-6-3", size: "", quantity: 1 },
  { name: "Grand medical", location: "1-9-3,, 5", size: "", quantity: 3 },
  { name: "H15 patio", location: "1-9-1", size: "", quantity: 1 },
  { name: "Hard rock Cafe", location: "4-6-1,2", size: "", quantity: 2 },
  { name: "Heban", location: "3-5-1, 2", size: "", quantity: 2 },
  { name: "Heksagon", location: "2-3-26", size: "", quantity: 1 },
  { name: "Helly hansen", location: "1-10-11,, 12", size: "", quantity: 2 },
  { name: "Helly hansen", location: "1-10-6, 7", size: "", quantity: 2 },
  { name: "Hiloft", location: "1-9-2", size: "", quantity: 1 },
  { name: "Honda", location: "4-2-1", size: "", quantity: 1 },
  { name: "Honda", location: "4-7-5", size: "", quantity: 1 },
  { name: "Hospittal", location: "1-11-21", size: "", quantity: 1 },
  { name: "Hotel 500", location: "3-4-10", size: "", quantity: 1 },
  { name: "Hotel Mikołajki", location: "1-5-7,-9,", size: "", quantity: 3 },
  { name: "Hotel Mikołajki", location: "4-7-6", size: "", quantity: 1 },
  { name: "Hunnebeck", location: "2-4-19", size: "", quantity: 1 },
  { name: "Hunnebeck", location: "2-5-19,, 20", size: "", quantity: 2 },
  { name: "Hunnebeck", location: "2-6-19,20", size: "", quantity: 2 },
  { name: "Hunnebeck", location: "3-5-3", size: "", quantity: 1 },
  { name: "Hunnebeck", location: "3-6-4", size: "", quantity: 1 },
  { name: "Hush Office", location: "1-11-13,,14", size: "", quantity: 2 },
  { name: "IQ marketing", location: "1-2-25", size: "", quantity: 0 },
  { name: "Ibis styles", location: "2-5-17,,18", size: "", quantity: 2 },
  { name: "Int Group (Jnt Group)", location: "2-4-16", size: "", quantity: 1 },
  { name: "Interfiber", location: "2-7-15", size: "", quantity: 1 },
  { name: "Intersnack", location: "2-10-15", size: "", quantity: 1 },
  { name: "Jan sander", location: "1-10-15", size: "", quantity: 1 },
  { name: "Jassmine", location: "1-3-8,10", size: "", quantity: 3 },
  { name: "Jazbud", location: "1-3-20", size: "", quantity: 1 },
  { name: "Jumpout", location: "3-1-3", size: "", quantity: 1 },
  { name: "Jungheinrich", location: "3-6-6", size: "", quantity: 1 },
  { name: "Just beck", location: "1-12-26", size: "", quantity: 1 },
  { name: "Kam", location: "1-4-12", size: "", quantity: 1 },
  { name: "Kam", location: "1-5-12,13", size: "", quantity: 2 },
  { name: "Kamienica 111A", location: "2-6-12", size: "", quantity: 1 },
  { name: "Katcon polska", location: "1-6-24", size: "", quantity: 1 },
  { name: "Kia", location: "1-1-5", size: "", quantity: 1 },
  { name: "Kia", location: "1-1-6", size: "", quantity: 1 },
  { name: "Kinder garden", location: "1-7-11,,19", size: "", quantity: 9 },
  { name: "King kong tha", location: "2-6-18", size: "", quantity: 1 },
  { name: "Klinika młodości", location: "2-11-5", size: "", quantity: 1 },
  { name: "Knight frank", location: "2-11-16, 17", size: "", quantity: 2 },
  { name: "Koki", location: "4-4-2", size: "", quantity: 1 },
  { name: "Koliber", location: "1-7-6", size: "", quantity: 1 },
  { name: "Koliber", location: "1-8-5", size: "", quantity: 1 },
  { name: "Kolmet", location: "1-6-25,,26,", size: "", quantity: 2 },
  { name: "Kolorowe Gary", location: "1-9-6,, 7", size: "", quantity: 2 },
  { name: "Kolumna park", location: "2-3-18", size: "", quantity: 1 },
  { name: "Kolumna park", location: "2-4-18", size: "", quantity: 1 },
  { name: "Kolumna park", location: "4-6-10", size: "", quantity: 1 },
  { name: "Komatsu", location: "1-8-1", size: "", quantity: 1 },
  { name: "Komeko", location: "2-8-19", size: "", quantity: 1 },
  { name: "Kominki Ostrowski", location: "2-11-7, 8", size: "", quantity: 2 },
  { name: "Kominki Ostrowski", location: "2-3-11", size: "", quantity: 1 },
  { name: "Kongsberg", location: "2-10-6", size: "", quantity: 1 },
  { name: "Kongsberg", location: "4-7-10", size: "", quantity: 1 },
  { name: "Kongsberg auto", location: "2-9-11", size: "", quantity: 1 },
  { name: "Kotniz", location: "1-7-3", size: "", quantity: 1 },
  { name: "Krajowa", location: "3-1-6,7", size: "", quantity: 2 },
  { name: "Krowy", location: "2-8-24", size: "", quantity: 1 },
  { name: "Krowy", location: "3-3-5", size: "", quantity: 1 },
  { name: "Leasys", location: "1-11-7,10", size: "", quantity: 4 },
  { name: "Lekarka wlk", location: "2-7-9", size: "", quantity: 1 },
  { name: "Len bawełna", location: "1-3-22", size: "", quantity: 1 },
  { name: "Len bawełna", location: "1-6-21", size: "", quantity: 1 },
  { name: "Lewiatan", location: "2-7-7", size: "", quantity: 1 },
  { name: "Lexus", location: "4-5-1", size: "", quantity: 1 },
  { name: "Liberty corner", location: "2-8-3,5", size: "", quantity: 3 },
  { name: "Liberty corner", location: "2-9-1", size: "", quantity: 1 },
  { name: "Liceum dalego", location: "1-4-10", size: "", quantity: 2 },
  { name: "Lipari", location: "1-6-23", size: "", quantity: 1 },
  { name: "Lipari", location: "1-7-21", size: "", quantity: 1 },
  { name: "Loreal", location: "3-6-11", size: "", quantity: 1 },
  { name: "Loreal mono", location: "1-6-23", size: "", quantity: 1 },
  { name: "Loreal mono", location: "1-7-22", size: "", quantity: 1 },
  { name: "Lsc communication", location: "4-2-3", size: "", quantity: 1 },
  { name: "Luba dental", location: "1-10-16", size: "", quantity: 2 },
  { name: "Lukasiewicz auto", location: "2-10-8", size: "", quantity: 1 },
  { name: "Madison", location: "2-6-11", size: "", quantity: 1 },
  { name: "Madison", location: "3-6-10", size: "", quantity: 1 },
  { name: "Makro", location: "2-10-3,4", size: "", quantity: 2 },
  { name: "Manifaktura", location: "2-4-22", size: "", quantity: 1 },
  { name: "Manor house", location: "2-8-13", size: "", quantity: 1 },
  { name: "Manor house", location: "3-8-8,, 11", size: "", quantity: 4 },
  { name: "Mars petcare", location: "4-2-8", size: "", quantity: 1 },
  { name: "Masters", location: "2-6-16", size: "", quantity: 1 },
  { name: "Matcars", location: "1-5-15", size: "", quantity: 1 },
  { name: "Max frank", location: "1-11-17,, 19", size: "", quantity: 3 },
  { name: "Mazovia hotel", location: "3-5-10", size: "", quantity: 1 },
  { name: "Mazowsze rest", location: "2-3-20", size: "", quantity: 1 },
  { name: "Mazurkas", location: "1-12-3,,5", size: "", quantity: 2 },
  { name: "Mazurkas", location: "3-2-1, 2", size: "", quantity: 2 },
  { name: "Mazurkas", location: "3-7-2, 3", size: "", quantity: 2 },
  { name: "Mazurkas", location: "3-7-6,7", size: "", quantity: 2 },
  { name: "Meblotap", location: "3-3-3", size: "", quantity: 1 },
  { name: "Medyk", location: "2-6-4", size: "", quantity: 1 },
  { name: "Mera WTK (Regał)", location: "", size: "", quantity: 16 },
  { name: "Mercure wiazo", location: "3-1-8", size: "", quantity: 1 },
  { name: "Mg pgd", location: "3-8-3", size: "", quantity: 1 },
  { name: "Mg pgd grupa", location: "1-11-25", size: "", quantity: 1 },
  { name: "Mini Europa", location: "3-2-7,8", size: "", quantity: 2 },
  { name: "Mini raj", location: "1-7-25", size: "", quantity: 1 },
  { name: "Mio", location: "1-12-11", size: "", quantity: 1 },
  { name: "Miromix 100x120", location: "2-1-21", size: "", quantity: 1 },
  { name: "Mk Szuster", location: "1-1-23", size: "", quantity: 1 },
  { name: "Mochowo", location: "1-3-25, 26", size: "", quantity: 2 },
  { name: "Mochowo", location: "2-10-26", size: "", quantity: 1 },
  { name: "Mochowo hubalcz", location: "2-4-26", size: "", quantity: 1 },
  { name: "Mochowo hubalcz", location: "2-9-26", size: "", quantity: 1 },
  { name: "Modelowanie sylwetki", location: "2-10-1", size: "", quantity: 1 },
  { name: "Modlin", location: "2-8-1, 2", size: "", quantity: 2 },
  { name: "Modlin", location: "3-5-5", size: "", quantity: 1 },
  { name: "Monkey Love", location: "1-3-19", size: "", quantity: 1 },
  { name: "Mono symfonia", location: "2-10-10,11", size: "", quantity: 2 },
  { name: "Motylkowa", location: "1-4-10", size: "", quantity: 2 },
  { name: "Msn", location: "4-3-1,2", size: "", quantity: 2 },
  { name: "Mytlewski cuk.", location: "1-4-6", size: "", quantity: 1 },
  { name: "Młyn smaków", location: "1-6-13", size: "", quantity: 1 },
  { name: "Ndap", location: "3-3-7", size: "", quantity: 1 },
  { name: "Netto", location: "1-7-24", size: "", quantity: 1 },
  { name: "Niewinni czarodzieje", location: "1-6-9", size: "", quantity: 1 },
  { name: "Noelle", location: "2-0-3", size: "", quantity: 1 },
  { name: "Noelle", location: "2-1-2", size: "", quantity: 1 },
  { name: "Noelle", location: "2-2-2", size: "", quantity: 1 },
  { name: "Nolita", location: "2-11-4", size: "", quantity: 1 },
  { name: "Nordson", location: "2-11-11,,15", size: "", quantity: 5 },
  { name: "Nowy gurewicz", location: "2-2-10,,11", size: "", quantity: 2 },
  { name: "Nowy gurewicz", location: "4-1-6", size: "", quantity: 1 },
  { name: "Olimpia fitness", location: "1-11-5,, 6", size: "", quantity: 2 },
  { name: "Omc", location: "1-8-19,,24", size: "", quantity: 6 },
  { name: "Optoton", location: "2-4-15", size: "", quantity: 1 },
  { name: "Optyk rekas", location: "2-9-7, 8", size: "", quantity: 2 },
  { name: "Optyk trzaska", location: "1-11-15", size: "", quantity: 1 },
  { name: "Optyk trzaska", location: "1-8-17", size: "", quantity: 1 },
  { name: "Optyk trzaska", location: "3-3-11", size: "", quantity: 1 },
  { name: "Optyk trzaska", location: "3-7-11", size: "", quantity: 1 },
  { name: "Orient massage", location: "1-6-8", size: "", quantity: 1 },
  { name: "Oriflame", location: "4-3-8,, 11", size: "", quantity: 4 },
  { name: "Orion", location: "4-7-1,, 3", size: "", quantity: 3 },
  { name: "Orlen elis", location: "2-3-19", size: "", quantity: 1 },
  { name: "PDC", location: "3-1-4", size: "", quantity: 1 },
  { name: "Palium", location: "2-10-2,3", size: "", quantity: 2 },
  { name: "Palium", location: "2-11-2", size: "", quantity: 1 },
  { name: "Palium", location: "2-11-26", size: "", quantity: 1 },
  { name: "Pas a pas", location: "2-11-1", size: "", quantity: 1 },
  { name: "Patron", location: "2-10-12,13", size: "", quantity: 2 },
  { name: "Patt mebel", location: "1-3-7", size: "", quantity: 1 },
  { name: "Patt mebel", location: "2-9-6", size: "", quantity: 1 },
  { name: "Patt mebel", location: "3-1-8", size: "", quantity: 1 },
  { name: "People cam fly", location: "4-7-4", size: "", quantity: 1 },
  { name: "People can fly", location: "4-6-4", size: "", quantity: 1 },
  { name: "Pg", location: "2-1-25", size: "", quantity: 1 },
  { name: "Pilar", location: "4-4-7", size: "", quantity: 1 },
  { name: "Pit stops", location: "2-8-21", size: "", quantity: 1 },
  { name: "Pitagoras Cafe", location: "2-6-15", size: "", quantity: 1 },
  { name: "Plac bankowy11", location: "", size: "", quantity: 0 },
  { name: "Plac przym 6", location: "2-4-24", size: "", quantity: 1 },
  { name: "Plac przym6", location: "2-4-24", size: "", quantity: 1 },
  { name: "Platinum cast", location: "2-8-14", size: "", quantity: 1 },
  { name: "Podosfera", location: "2-10-9", size: "", quantity: 1 },
  { name: "Pokusa kebab", location: "1-4-21-24", size: "", quantity: 4 },
  { name: "Polswiss art", location: "2-3-1", size: "", quantity: 1 },
  { name: "Potocka", location: "1-6-14,,-17,,", size: "", quantity: 4 },
  { name: "Powidoki", location: "2-9-21", size: "", quantity: 1 },
  { name: "Premium fitness", location: "2-9-14", size: "", quantity: 1 },
  { name: "Prima vita", location: "2-3-25", size: "", quantity: 1 },
  { name: "Procural", location: "3-7-4,5", size: "", quantity: 2 },
  { name: "Przedszkole Suwałki", location: "1-7-26", size: "", quantity: 1 },
  { name: "Przyjaciel", location: "3-4-5", size: "", quantity: 1 },
  { name: "Quercia", location: "2-0-1", size: "", quantity: 1 },
  { name: "Raubic", location: "2-6-9,10", size: "", quantity: 1 },
  { name: "Raubic", location: "2-8-9,,11", size: "", quantity: 3 },
  { name: "Rbt", location: "2-7-17,18", size: "", quantity: 2 },
  { name: "React", location: "1-12-6,,10", size: "", quantity: 5 },
  { name: "Rebel", location: "1-7-20", size: "", quantity: 1 },
  { name: "Reckitt", location: "4-1-3", size: "", quantity: 1 },
  { name: "Reckitt", location: "4-1-4", size: "", quantity: 1 },
  { name: "Reckitt", location: "4-2-2", size: "", quantity: 1 },
  { name: "Reckitt nowy", location: "", size: "", quantity: 0 },
  { name: "Rehadent", location: "2-8-15", size: "", quantity: 1 },
  { name: "Reytan", location: "2-8-22", size: "", quantity: 1 },
  { name: "Reytan", location: "3-3-4", size: "", quantity: 1 },
  { name: "Rezydencja Sobieskiego", location: "1-3-4", size: "", quantity: 1 },
  { name: "Rk niedziałek", location: "3-1-10,11", size: "", quantity: 2 },
  { name: "Rodl partner", location: "1-6-10,11", size: "", quantity: 3 },
  { name: "Rodl partner", location: "1-8-12", size: "", quantity: 1 },
  { name: "Rodl partner", location: "3-5-11", size: "", quantity: 1 },
  { name: "Ronson", location: "1-9-17,,18", size: "", quantity: 2 },
  { name: "Ronson", location: "1-9-21,,24", size: "", quantity: 4 },
  { name: "Route", location: "2-7-3", size: "", quantity: 1 },
  { name: "Rudolf", location: "1-1-11", size: "", quantity: 1 },
  { name: "Rudolf", location: "1-1-11", size: "", quantity: 1 },
  { name: "Rudolf", location: "1-1-13", size: "", quantity: 1 },
  { name: "Różański", location: "2-9-18", size: "", quantity: 1 },
  { name: "Sailor", location: "2-5-16", size: "", quantity: 1 },
  { name: "Salon win i alk", location: "2-7-6", size: "", quantity: 1 },
  { name: "Santi", location: "2-10-22,,25", size: "", quantity: 4 },
  { name: "Scarabeus", location: "1-6-12", size: "", quantity: 1 },
  { name: "Schomburg", location: "2-7-12 do 14", size: "", quantity: 3 },
  { name: "Scolar", location: "2-9-12, 13", size: "", quantity: 2 },
  { name: "Scraper", location: "2-6-17", size: "", quantity: 1 },
  { name: "Seka", location: "2-7-4,5", size: "", quantity: 2 },
  { name: "Sew euro", location: "4-6-8", size: "", quantity: 1 },
  { name: "Shock", location: "1-4-9", size: "", quantity: 1 },
  { name: "Silver screen", location: "3-2-10,11", size: "", quantity: 2 },
  { name: "Siro", location: "1-3-1", size: "", quantity: 1 },
  { name: "Skylight", location: "1-11-12", size: "", quantity: 1 },
  { name: "Skylight", location: "1-12-12,,17", size: "", quantity: 6 },
  { name: "Skylight", location: "3-5-9", size: "", quantity: 1 },
  { name: "Smile team", location: "2-2-9", size: "", quantity: 1 },
  { name: "Sofitel", location: "3-1-1, 2", size: "", quantity: 2 },
  { name: "Sponcel", location: "1-4-25", size: "", quantity: 1 },
  { name: "Stacja grawitacja (Regał) fiolet", location: "", size: "", quantity: 0 },
  { name: "Stacja grawitacja (czarna,tam gdzie fiolet )", location: "", size: "", quantity: 1 },
  { name: "Stacja grawitacja", location: "3-7-8,9", size: "", quantity: 2 },
  { name: "Stara kamienica", location: "2-10-18", size: "", quantity: 1 },
  { name: "Stara kamienica", location: "3-4-9", size: "", quantity: 1 },
  { name: "Starpol", location: "3-3-6", size: "", quantity: 1 },
  { name: "Stomatologia", location: "2-2-20", size: "", quantity: 1 },
  { name: "Stomatologia", location: "2-2-21", size: "", quantity: 1 },
  { name: "Stomatologia", location: "2-3-23", size: "", quantity: 1 },
  { name: "Stomatologia", location: "2-3-24", size: "", quantity: 1 },
  { name: "Strabag", location: "2-6-24,, 26", size: "", quantity: 3 },
  { name: "Strabag", location: "4-5-4", size: "", quantity: 1 },
  { name: "Strabag czerwona", location: "4-6-9", size: "", quantity: 1 },
  { name: "Strabag ozik", location: "2-1-18,,19", size: "", quantity: 2 },
  { name: "Student depot", location: "", size: "", quantity: 0 },
  { name: "Studio figura stm", location: "3-2-3", size: "", quantity: 1 },
  { name: "Studio figura ząbki", location: "2-9-23.24", size: "", quantity: 2 },
  { name: "Studio17", location: "2-9-2, 3", size: "", quantity: 2 },
  { name: "Summer Sun", location: "2-3-21", size: "", quantity: 1 },
  { name: "Supremis", location: "1-1-1", size: "", quantity: 1 },
  { name: "Suzuki", location: "1-10-25", size: "", quantity: 1 },
  { name: "Suzuki", location: "1-10-26", size: "", quantity: 1 },
  { name: "Suzuki", location: "1-9-25", size: "", quantity: 0 },
  { name: "Suzuki", location: "2-0-25", size: "", quantity: 1 },
  { name: "Suzuki", location: "2-0-25", size: "", quantity: 1 },
  { name: "Suzuki", location: "2-11-18,,20", size: "", quantity: 3 },
  { name: "Suzuki", location: "2-9-25", size: "", quantity: 1 },
  { name: "Suzuki motors", location: "2-4-5,,14", size: "", quantity: 10 },
  { name: "Suzuki motors", location: "2-5-3,,12", size: "", quantity: 10 },
  { name: "Suzuki motors", location: "2-6-2,,3", size: "", quantity: 2 },
  { name: "Szara 190x115", location: "2-5-26", size: "", quantity: 1 },
  { name: "Szkoła pwdn", location: "2-11-25", size: "", quantity: 1 },
  { name: "Szkoła pwdn", location: "3-1-5", size: "", quantity: 1 },
  { name: "Szpulka łódz", location: "2-10-14", size: "", quantity: 1 },
  { name: "Szron", location: "1-2-12", size: "", quantity: 1 },
  { name: "Słodki słony fam", location: "2-7-11", size: "", quantity: 1 },
  { name: "Tagomago boutique", location: "1-8-26", size: "", quantity: 1 },
  { name: "Teo", location: "3-8-4", size: "", quantity: 1 },
  { name: "Termalny hotel", location: "2-2-2", size: "", quantity: 1 },
  { name: "Terminus", location: "2-4-25", size: "", quantity: 1 },
  { name: "Thai organic", location: "1-7-7", size: "", quantity: 1 },
  { name: "The tides", location: "3-8-5", size: "", quantity: 1 },
  { name: "Tip", location: "2-1-15 oraz 2-3-15", size: "", quantity: 2 },
  { name: "Tip", location: "2-1-16", size: "", quantity: 1 },
  { name: "Tiramisu", location: "1-2-9", size: "", quantity: 1 },
  { name: "Tobaco", location: "1-11-20", size: "", quantity: 1 },
  { name: "Toni", location: "1-8-3", size: "", quantity: 1 },
  { name: "Toyota", location: "1-10-23,, 24", size: "", quantity: 2 },
  { name: "Trans", location: "2-8-12", size: "", quantity: 1 },
  { name: "Traveliada", location: "2-1-20", size: "", quantity: 1 },
  { name: "Tuberoza", location: "1-2-2", size: "", quantity: 1 },
  { name: "Tuberoza", location: "1-2-3", size: "", quantity: 1 },
  { name: "Tyvodar jawellery", location: "3-4-7", size: "", quantity: 1 },
  { name: "Ukryte rzeki", location: "2-9-19", size: "", quantity: 1 },
  { name: "Ulik", location: "1-4-19", size: "", quantity: 1 },
  { name: "Ulik", location: "2-3-2", size: "", quantity: 1 },
  { name: "Ulik", location: "2-4-3,,4", size: "", quantity: 2 },
  { name: "Uroves", location: "2-1-1 oraz 2-4-1", size: "", quantity: 2 },
  { name: "Ursapharm", location: "4-5,5,6", size: "", quantity: 2 },
  { name: "VS akademia urody", location: "2-1-22,23", size: "", quantity: 2 },
  { name: "Varto restaurant", location: "2-2-1", size: "", quantity: 1 },
  { name: "Veolia", location: "2-7-19,20", size: "", quantity: 2 },
  { name: "Victoria wellness", location: "2-10-16", size: "", quantity: 1 },
  { name: "Villa mia", location: "1-5-16", size: "", quantity: 1 },
  { name: "Villa riccona", location: "4-4-5", size: "", quantity: 1 },
  { name: "W&L", location: "3-3-2", size: "", quantity: 1 },
  { name: "WTT", location: "", size: "", quantity: 0 },
  { name: "Warszawa oper kamer", location: "1-3-17, 18", size: "", quantity: 2 },
  { name: "Warszawa oper kamer", location: "4-2-4", size: "", quantity: 1 },
  { name: "Warszawa opera kamer", location: "4-1-5", size: "", quantity: 1 },
  { name: "Warszawa wschodnia", location: "3-4-6", size: "", quantity: 1 },
  { name: "Whiskey", location: "3-8-6", size: "", quantity: 1 },
  { name: "Whiskey unic", location: "2-10-19-20", size: "", quantity: 2 },
  { name: "Willa brzegi", location: "2-7-23", size: "", quantity: 1 },
  { name: "Winterhalter", location: "2-7-24", size: "", quantity: 1 },
  { name: "Wise point", location: "", size: "", quantity: 7 },
  { name: "Wiązowna apteka", location: "1-8-10", size: "", quantity: 1 },
  { name: "Wodkan", location: "1-5-24", size: "", quantity: 0 },
  { name: "Wola center", location: "3-8-7 ( lub na stole)", size: "", quantity: 1 },
  { name: "Wsi", location: "2-6-13, 14", size: "", quantity: 2 },
  { name: "Wybitnie niez.", location: "pod małymi żabkami 85x75", size: "", quantity: 2 },
  { name: "Xylem", location: "1-10-1,, 5", size: "", quantity: 5 },
  { name: "Yumi sushi", location: "2-8-6", size: "", quantity: 1 },
  { name: "Yuniversal", location: "1-8-4", size: "", quantity: 1 },
  { name: "Zacisze Urody", location: "1-1-10", size: "", quantity: 1 },
  { name: "Zala", location: "1-12-1", size: "", quantity: 1 },
  { name: "Zasada", location: "1-10-13", size: "", quantity: 1 },
  { name: "Zasada", location: "3-4-8", size: "", quantity: 1 },
  { name: "Zaułek piękna", location: "2-5-21,, 24", size: "", quantity: 4 },
  { name: "Zon clinic", location: "2-11-3", size: "", quantity: 1 },
  { name: "Zon clinic", location: "2-9-4,5", size: "", quantity: 2 },
  { name: "Zs16 sto", location: "2-11-9", size: "", quantity: 1 },
  { name: "Żurawia 6/12", location: "2-2-3", size: "", quantity: 1 },
];
